### ISSUE TITLE
Plan działania fazy 3

### ISSUE THREAD

**Issue by MarcinKosinski** [MarcinKosinski/MoviesBigDataScience#2]
Zgodnie z treścią zadania:

> C. Celem jest zbudowanie usługi internetowej opartej o zebrane dane o filmach. Aplikacja może być > dostępna jako pakiet w R, jako serwis REST lub jako aplikacja shiny. [max 20 punktów]

Proponuję zrobić aplikację shiny, ktora bazowawalaby na 3 policzonych juz naszych macierzach, jednak nasze macierze sa strasznie grube. Maja po okolo 250-300 mb.

Proponowany plan dzialania:
1. Przemyslec metode odchudzenia macierzy podobienstw.
2. Przemyslec metode prezentacji graficznej podobienstw filmow; graf albo mapa ciepla, albo cos innego.
3. Przemyslec funkcjonalnosc aplikacji.
4. Zaimplementowac powyzsze.

**Comment by MarcinKosinski** [comment]
Ja osobiscie moge zglosic sie do przygotowania aplikacji shiny albo aplikacji shinydashboard i do przemyslanie jak odchudzic nasze macierze odleglosci. Dodatkowo pamietajmy, ze ogolnie analizujemy 9000 pierwszych filmow z  listy `popularne`? Czy jak to tam bylo?

**Comment by grabarze** [comment]
9k filmow najpopulatniejszych,z heatmapy nie wiem czy cos bedzie widac; mysle ze w aplikacji wybierasz film i wprowadzasz te wagi co sie lda Ciebie liczy, potem bedziesz wybieral z 3 macierzy te filmy, pomnozysz te podobienstwa przez wagi i wyplujjesz iles tam np 20 podobnych

**Comment by grabarze** [comment]
ochcucidzic nie iwem, one sa symetryczne to mozna polowe opierdolic
